package component:add;

interface types {
  enum operation {
    add,
    sub
  }

  resource engine {
    constructor();
    push-operand: func(operand: u32);
    push-operation: func(operation: operation);
    execute: func() -> u32;
  }
}

/// An example world for the component to target.
world calculator {
    export types;
}
